export const INIT = 'SOCKET_INITIALIZATION';
export const PUT = 'PUT_SOCKET';
export const CONNECTION_SUCCEEDED = 'SOCKET_CONNECTION_SUCCEEDED';
export const CONNECTION_FAILED = 'SOCKET_CONNECTION_ERROR';
export const DISCONNECTION = 'SOCKET_DISCONNECTION';
export const RECONNECTION_SUCCEEDED = 'SOCKET_RECONNECTION_SUCCEEDED';
export const RECONNECTION_FAILED = 'SOCKET_RECONNECTION_FAILED';