export const AUTH_REQUESTED = 'AUTH_REQUESTED';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_SUCCEEDED = 'AUTH_SUCCEEDED';

export const FETCHING_CURRENT_USER_REQUESTED = 'FETCHING_CURRENT_USER_REQUESTED';
export const FETCHING_CURRENT_USER_FAILED = 'FETCHING_CURRENT_USER_FAILED';
export const FETCHING_CURRENT_USER_SUCCEEDED = 'FETCHING_CURRENT_USER_SUCCEEDED';