export const CREATION_REQUESTED = 'USER_CREATION_REQUESTED';
export const CREATION_FAILED = 'USER_CREATION_FAILED';
export const CREATION_SUCCEDDED = 'USER_CREATION_SUCCEEDED';
export const FETCHING_SUCCEDED = 'USERS_FETCHING_SUCCEEDED';
export const FETCHING_FAILED = 'USERS_FETCHING_FAILED';
export const TYPING_STARTED = 'USER_STARTED_TYPING';
export const TYPING_FINISHED= 'USER_FINISHED_TYPING';